#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 28.10.2019 13:08
# Generated By: Aaron Gensetter
# For M143-Backup-and-Restore
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$error = "false"
$logfile = "false"
$form1 = New-Object System.Windows.Forms.Form
$rdo_restore = New-Object System.Windows.Forms.RadioButton
$chb_timer = New-Object System.Windows.Forms.CheckBox
$numupd_timer = New-Object System.Windows.Forms.NumericUpDown
$rdo_differential = New-Object System.Windows.Forms.RadioButton
$rdo_incremental = New-Object System.Windows.Forms.RadioButton
$rdo_full_backup = New-Object System.Windows.Forms.RadioButton
$lbl_status = New-Object System.Windows.Forms.Label
$btn_backup_start = New-Object System.Windows.Forms.Button
$lbl_backup = New-Object System.Windows.Forms.Label
$btn_fileDialog3 = New-Object System.Windows.Forms.Button
$txb_path_3 = New-Object System.Windows.Forms.TextBox
$chb_logfile = New-Object System.Windows.Forms.CheckBox
$lbl_destination = New-Object System.Windows.Forms.Label
$lbl_source = New-Object System.Windows.Forms.Label
$txb_path_2 = New-Object System.Windows.Forms.TextBox
$btn_fileDialog2 = New-Object System.Windows.Forms.Button
$txb_path_1 = New-Object System.Windows.Forms.TextBox
$btn_fileDialog1 = New-Object System.Windows.Forms.Button
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$click_inc= 
{
#TODO: Place custom script here

}

$handler_lbl_destination_Click= 
{
#TODO: Place custom script here

}

$click_logfile_chb= 
{
    $txb_path_3.Enabled = $chb_logfile.Checked
    $btn_fileDialog3.Enabled = $chb_logfile.Checked

}

$click_repeat_after= 
{
$numupd_timer.Enabled = $chb_timer.Checked

}

$click_fileDialog3= 
{
    Add-Type -AssemblyName System.Windows.Forms
    $FolderBrowser3 = New-Object System.Windows.Forms.FolderBrowserDialog
    [void]$FolderBrowser3.ShowDialog()

    $txb_path_3.text = $FolderBrowser3.SelectedPath

}

$handler_radioButton3_CheckedChanged= 
{
#TODO: Place custom script here

}

$Click_backup_start= 
{
    #RESTORE
    if($rdo_restore.Checked) {
        #überprüfen ob textboxen ausgefüllt sind
        if($chb_logfile.Checked -eq $true){
            $logfile = "true"
            if ($txb_path_3.text -eq ""){
                $error = "true"
                $lbl_status.text = "> Logfile Pfad bitte ausfüllen!"
            } 
        }
        if($txb_path_1.text -eq ""){
            $error = "true"
            $lbl_status.text = "> Quell Pfad bitte ausfüllen!"
        } 
        if($txb_path_2.text -eq ""){
            $error = "true"
            $lbl_status.text = "> Ziel Pfad bitte ausfüllen!"
        } 

        # überprüfen ob Pfad existiert
        if($error -ne "true") {
            $test_path_1 = Test-Path $txb_path_1.text
            $test_path_2 =Test-Path $txb_path_2.text
            if($test_path_1 -ne "True") {
                $error = "true"
                $lbl_status.text = "> Quellpfad Existiert nicht!"
            }
            if($test_path_2 -ne "True") {
                $error = "true"
                $lbl_status.text = "> Zielpfad Existiert nicht!"
            }
            if ($logfile -eq "true") {
                $test_path_3 =Test-Path $txb_path_3.text
                if($test_path_3 -ne "True") {
                    $error = "true"
                    $lbl_status.text = "> Logfile pfad Existiert nicht!"
                }
            }
        }
        # überprüfen ob Quell- und Zielpfad verschieden sind
        if($error -ne "true"){
            if($txb_path_1.text -eq $txb_path_2.text) {
               $error = "true"
               $lbl_status.text = "> Quell- und Zielpfad führen zum gleichen verzeichniss!" 
            }
        }
         # Ausführen des Kopierensvorganges
        if($error -ne "true"){
        
            if($logfile -eq "true") {
                $logpath = $txb_path_3.text
                $date = get-date -Format "yyyy-MM-dd-HH_mm_ss"
                $logfile_path = "/LOG:$logpath\$date.txt";
            }
                $src = $txb_path_2.text
                $dest = $txb_path_1.text

                robocopy "$src" "$dest" /E "$logfile_path"


            $lbl_status.text = ">  Restore wurde gestartet!"
        }
    } else {
    #BACKUP
    #überprüfen ob textboxen ausgefüllt sind
    if($chb_logfile.Checked -eq $true){
        $logfile = "true"
        if ($txb_path_3.text -eq ""){
            $error = "true"
            $lbl_status.text = "> Logfile Pfad bitte ausfüllen!"
        } 
    }
    if($chb_timer.Checked -eq $true){
        $timer = "true"
        if([int]$numupd_timer.text -le 0) {
            $error = "true"
            $lbl_status.text = ">  Der Timer darf nicht kleiner als '0' sein!"
        }
    }
    if($txb_path_1.text -eq ""){
        $error = "true"
        $lbl_status.text = "> Quell Pfad bitte ausfüllen!"
    } 
    if($txb_path_2.text -eq ""){
        $error = "true"
        $lbl_status.text = "> Ziel Pfad bitte ausfüllen!"
    } 

    # überprüfen ob Pfad existiert
    if($error -ne "true") {
        $test_path_1 = Test-Path $txb_path_1.text
        $test_path_2 =Test-Path $txb_path_2.text
        if($test_path_1 -ne "True") {
            $error = "true"
            $lbl_status.text = "> Quellpfad Existiert nicht!"
        }
        if($test_path_2 -ne "True") {
            $error = "true"
            $lbl_status.text = "> Zielpfad Existiert nicht!"
        }
        if ($logfile -eq "true") {
            $test_path_3 =Test-Path $txb_path_3.text
            if($test_path_3 -ne "True") {
                $error = "true"
                $lbl_status.text = "> Logfile pfad Existiert nicht!"
            }
        }
    }
    # überprüfen ob Quell- und Zielpfad verschieden sind
    if($error -ne "true"){
        if($txb_path_1.text -eq $txb_path_2.text) {
           $error = "true"
           $lbl_status.text = "> Quell- und Zielpfad führen zum gleichen verzeichniss!" 
        }
    }
    # Ausführen des Kopierensvorganges
    if($error -ne "true"){
        $date = get-date -Format "yyyy-MM-dd-HH_mm_ss"
        $txb_path_2_tmp = $txb_path_2.text
        if($logfile -eq "true") {
            $logpath = $txb_path_3.text
            $logfile_path = "/LOG:$logpath\$date.txt";
        }
        if($timer -eq "true") {
            $tim = "true "
            $time = [int]$numupd_timer.text * 60
            $timer_path = "/MOT:$time"
        }
        if($rdo_full_backup.checked) {
            $backuptype = '/E /Z /R:10 /W:10'
            $backup_msg = "FULLBACKUP"
        } elseif($rdo_incremental.checked) {
            $backuptype = '/S /Z /R:10 /W:10 /M'
            $backup_msg = "INCREMENTAL"
            $txb_path_2_tmp = $txb_path_2.text
            $txb_path_2.Text = "$txb_path_2_tmp\$date"
        } elseif($rdo_differential.checked) {
            $backuptype = '/S /Z /R:10 /W:10 /A'
            $backup_msg = "DIFFERENTIAL"
            $txb_path_2_tmp = $txb_path_2.text
            $txb_path_2.Text = "$txb_path_2_tmp\$date"
        } else {
           $error = "true"
           $lbl_status.text = ">  Bitte Backupart wählen!"
        }
        # Backup Start

        if($error -ne "true") {
            $src = $txb_path_1.text
            $dest = $txb_path_2.text
            $robocopy = "robocopy $src $dest $logfile_path $timer_path $backuptype"
            write-host $robocopy
            Invoke-Expression $robocopy
            $txb_path_2.Text = $txb_path_2_tmp
            
            $lbl_status.text = ">  Backup wurde gestartet! Modus: $backup_msg"
        }
    }
    }

}

$handler_lbl_source_Click= 
{
#TODO: Place custom script here

}

$handler_radioButton1_CheckedChanged= 
{
#TODO: Place custom script here

}

$click_fileDialog1= 
{
    Add-Type -AssemblyName System.Windows.Forms
    $FolderBrowser1 = New-Object System.Windows.Forms.FolderBrowserDialog
    [void]$FolderBrowser1.ShowDialog()

    $txb_path_1.text = $FolderBrowser1.SelectedPath

}

$handler_label1_Click= 
{
#TODO: Place custom script here

}

$click_dif= 
{
#TODO: Place custom script here

}

$click_fileDialog2= 
{
    Add-Type -AssemblyName System.Windows.Forms
    $FolderBrowser2 = New-Object System.Windows.Forms.FolderBrowserDialog
    [void]$FolderBrowser2.ShowDialog()

    $txb_path_2.text = $FolderBrowser2.SelectedPath

}

$click_full= 
{
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 261
$System_Drawing_Size.Width = 499
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.FormBorderStyle = 1
$form1.Name = "form1"
$form1.Text = "Backup Programm"


$rdo_restore.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 284
$System_Drawing_Point.Y = 138
$rdo_restore.Location = $System_Drawing_Point
$rdo_restore.Name = "rdo_restore"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$rdo_restore.Size = $System_Drawing_Size
$rdo_restore.TabIndex = 18
$rdo_restore.TabStop = $True
$rdo_restore.Text = "Restore"
$rdo_restore.UseVisualStyleBackColor = $True
$rdo_restore.add_CheckedChanged($handler_radioButton1_CheckedChanged)

$form1.Controls.Add($rdo_restore)


$chb_timer.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 108
$chb_timer.Location = $System_Drawing_Point
$chb_timer.Name = "chb_timer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 120
$chb_timer.Size = $System_Drawing_Size
$chb_timer.TabIndex = 17
$chb_timer.Text = "Wiedeholong nach"
$chb_timer.UseVisualStyleBackColor = $True
$chb_timer.add_Click($click_repeat_after)

$form1.Controls.Add($chb_timer)

$numupd_timer.DataBindings.DefaultDataSourceUpdateMode = 0
$numupd_timer.Enabled = $False
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 138
$System_Drawing_Point.Y = 107
$numupd_timer.Location = $System_Drawing_Point
$numupd_timer.Name = "numupd_timer"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 260
$numupd_timer.Size = $System_Drawing_Size
$numupd_timer.TabIndex = 16

$form1.Controls.Add($numupd_timer)


$rdo_differential.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 197
$System_Drawing_Point.Y = 138
$rdo_differential.Location = $System_Drawing_Point
$rdo_differential.Name = "rdo_differential"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 81
$rdo_differential.Size = $System_Drawing_Size
$rdo_differential.TabIndex = 14
$rdo_differential.TabStop = $True
$rdo_differential.Text = "Differential"
$rdo_differential.UseVisualStyleBackColor = $True
$rdo_differential.add_Click($click_dif)
$rdo_differential.add_CheckedChanged($handler_radioButton3_CheckedChanged)

$form1.Controls.Add($rdo_differential)


$rdo_incremental.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 102
$System_Drawing_Point.Y = 138
$rdo_incremental.Location = $System_Drawing_Point
$rdo_incremental.Name = "rdo_incremental"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 89
$rdo_incremental.Size = $System_Drawing_Size
$rdo_incremental.TabIndex = 13
$rdo_incremental.TabStop = $True
$rdo_incremental.Text = "Incremental"
$rdo_incremental.UseVisualStyleBackColor = $True
$rdo_incremental.add_Click($click_inc)

$form1.Controls.Add($rdo_incremental)


$rdo_full_backup.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 11
$System_Drawing_Point.Y = 138
$rdo_full_backup.Location = $System_Drawing_Point
$rdo_full_backup.Name = "rdo_full_backup"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 85
$rdo_full_backup.Size = $System_Drawing_Size
$rdo_full_backup.TabIndex = 12
$rdo_full_backup.TabStop = $True
$rdo_full_backup.Text = "Full Backup"
$rdo_full_backup.UseVisualStyleBackColor = $True
$rdo_full_backup.add_Click($click_full)
$rdo_full_backup.add_CheckedChanged($handler_radioButton1_CheckedChanged)

$form1.Controls.Add($rdo_full_backup)

$lbl_status.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 238
$lbl_status.Location = $System_Drawing_Point
$lbl_status.Name = "lbl_status"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 475
$lbl_status.Size = $System_Drawing_Size
$lbl_status.TabIndex = 11
$lbl_status.Text = ">"
$lbl_status.add_Click($handler_label1_Click)

$form1.Controls.Add($lbl_status)


$btn_backup_start.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 406
$System_Drawing_Point.Y = 212
$btn_backup_start.Location = $System_Drawing_Point
$btn_backup_start.Name = "btn_backup_start"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 70
$btn_backup_start.Size = $System_Drawing_Size
$btn_backup_start.TabIndex = 10
$btn_backup_start.Text = "Starten"
$btn_backup_start.UseVisualStyleBackColor = $True
$btn_backup_start.add_Click($Click_backup_start)

$form1.Controls.Add($btn_backup_start)

$lbl_backup.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 406
$System_Drawing_Point.Y = 186
$lbl_backup.Location = $System_Drawing_Point
$lbl_backup.Name = "lbl_backup"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 70
$lbl_backup.Size = $System_Drawing_Size
$lbl_backup.TabIndex = 9
$lbl_backup.Text = "Backup"

$form1.Controls.Add($lbl_backup)


$btn_fileDialog3.DataBindings.DefaultDataSourceUpdateMode = 0
$btn_fileDialog3.Enabled = $False

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 364
$System_Drawing_Point.Y = 79
$btn_fileDialog3.Location = $System_Drawing_Point
$btn_fileDialog3.Name = "btn_fileDialog3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 34
$btn_fileDialog3.Size = $System_Drawing_Size
$btn_fileDialog3.TabIndex = 8
$btn_fileDialog3.Text = "..."
$btn_fileDialog3.UseVisualStyleBackColor = $True
$btn_fileDialog3.add_Click($click_fileDialog3)

$form1.Controls.Add($btn_fileDialog3)

$txb_path_3.DataBindings.DefaultDataSourceUpdateMode = 0
$txb_path_3.Enabled = $False
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 138
$System_Drawing_Point.Y = 81
$txb_path_3.Location = $System_Drawing_Point
$txb_path_3.Name = "txb_path_3"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 220
$txb_path_3.Size = $System_Drawing_Size
$txb_path_3.TabIndex = 7

$form1.Controls.Add($txb_path_3)


$chb_logfile.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 79
$chb_logfile.Location = $System_Drawing_Point
$chb_logfile.Name = "chb_logfile"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 120
$chb_logfile.Size = $System_Drawing_Size
$chb_logfile.TabIndex = 6
$chb_logfile.Text = "Logfile erstellen"
$chb_logfile.UseVisualStyleBackColor = $True
$chb_logfile.add_Click($click_logfile_chb)

$form1.Controls.Add($chb_logfile)

$lbl_destination.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 46
$lbl_destination.Location = $System_Drawing_Point
$lbl_destination.Name = "lbl_destination"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 64
$lbl_destination.Size = $System_Drawing_Size
$lbl_destination.TabIndex = 5
$lbl_destination.Text = "Zielordner"
$lbl_destination.add_Click($handler_lbl_destination_Click)

$form1.Controls.Add($lbl_destination)

$lbl_source.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 15
$lbl_source.Location = $System_Drawing_Point
$lbl_source.Name = "lbl_source"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 64
$lbl_source.Size = $System_Drawing_Size
$lbl_source.TabIndex = 4
$lbl_source.Text = "Quellordner"
$lbl_source.add_Click($handler_lbl_source_Click)

$form1.Controls.Add($lbl_source)

$txb_path_2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 82
$System_Drawing_Point.Y = 44
$txb_path_2.Location = $System_Drawing_Point
$txb_path_2.Name = "txb_path_2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 220
$txb_path_2.Size = $System_Drawing_Size
$txb_path_2.TabIndex = 3

$form1.Controls.Add($txb_path_2)


$btn_fileDialog2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 308
$System_Drawing_Point.Y = 43
$btn_fileDialog2.Location = $System_Drawing_Point
$btn_fileDialog2.Name = "btn_fileDialog2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 35
$btn_fileDialog2.Size = $System_Drawing_Size
$btn_fileDialog2.TabIndex = 2
$btn_fileDialog2.Text = "..."
$btn_fileDialog2.UseVisualStyleBackColor = $True
$btn_fileDialog2.add_Click($click_fileDialog2)

$form1.Controls.Add($btn_fileDialog2)

$txb_path_1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 82
$System_Drawing_Point.Y = 14
$txb_path_1.Location = $System_Drawing_Point
$txb_path_1.Name = "txb_path_1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 220
$txb_path_1.Size = $System_Drawing_Size
$txb_path_1.TabIndex = 1

$form1.Controls.Add($txb_path_1)


$btn_fileDialog1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 308
$System_Drawing_Point.Y = 13
$btn_fileDialog1.Location = $System_Drawing_Point
$btn_fileDialog1.Name = "btn_fileDialog1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 35
$btn_fileDialog1.Size = $System_Drawing_Size
$btn_fileDialog1.TabIndex = 0
$btn_fileDialog1.Text = "..."
$btn_fileDialog1.UseVisualStyleBackColor = $True
$btn_fileDialog1.add_Click($click_fileDialog1)

$form1.Controls.Add($btn_fileDialog1)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
