Clear-Host
# Funktion Main
function main {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 14.09.2019 14:13
# Generated By: Aaron Gensetter
# For M122-Abläufe-Automatisieren
########################################################################
#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$frm_init = New-Object System.Windows.Forms.Form
$btn_init_cancel = New-Object System.Windows.Forms.Button
$btn_init_grp_del = New-Object System.Windows.Forms.Button
$btn_init_usr_edit = New-Object System.Windows.Forms.Button
$lbl_user_edit = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$btn_init_grp_edit_click= 
{
    $frm_init.Hide() # hide form
    group-editor # open new form
    $frm_init.Show() # if new form colsed, open old

}

$btn_init_cancel_click= 
{
    $frm_init.Close() # Close current form

}

$btn_init_usr_edit_click= 
{
    $frm_init.Hide() # hide form
    user-editor # open new form
    $frm_init.Show() # if new form colsed, open old

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$frm_init.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 153
$System_Drawing_Size.Width = 349
$frm_init.ClientSize = $System_Drawing_Size
$frm_init.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_init.FormBorderStyle = 1
$frm_init.Name = "frm_init"
$frm_init.Text = "User and Group Editor"
$frm_init.add_Load($handler_frm_init_Load)


$btn_init_cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 121
$btn_init_cancel.Location = $System_Drawing_Point
$btn_init_cancel.Name = "btn_init_cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_init_cancel.Size = $System_Drawing_Size
$btn_init_cancel.TabIndex = 5
$btn_init_cancel.Text = "Cancel"
$btn_init_cancel.UseVisualStyleBackColor = $True
$btn_init_cancel.add_Click($btn_init_cancel_click)

$frm_init.Controls.Add($btn_init_cancel)


$btn_init_grp_del.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 92
$btn_init_grp_del.Location = $System_Drawing_Point
$btn_init_grp_del.Name = "btn_init_grp_del"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_init_grp_del.Size = $System_Drawing_Size
$btn_init_grp_del.TabIndex = 4
$btn_init_grp_del.Text = "Group Edit"
$btn_init_grp_del.UseVisualStyleBackColor = $True
$btn_init_grp_del.add_Click($btn_init_grp_edit_click)

$frm_init.Controls.Add($btn_init_grp_del)


$btn_init_usr_edit.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 63
$btn_init_usr_edit.Location = $System_Drawing_Point
$btn_init_usr_edit.Name = "btn_init_usr_edit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_init_usr_edit.Size = $System_Drawing_Size
$btn_init_usr_edit.TabIndex = 3
$btn_init_usr_edit.Text = "User Edit"
$btn_init_usr_edit.UseVisualStyleBackColor = $True
$btn_init_usr_edit.add_Click($btn_init_usr_edit_click)

$frm_init.Controls.Add($btn_init_usr_edit)

$lbl_user_edit.BorderStyle = 2
$lbl_user_edit.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_user_edit.Font = New-Object System.Drawing.Font("Tahoma",12,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_user_edit.Location = $System_Drawing_Point
$lbl_user_edit.Name = "lbl_user_edit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 325
$lbl_user_edit.Size = $System_Drawing_Size
$lbl_user_edit.TabIndex = 1
$lbl_user_edit.Text = "User and Group Editor"
$lbl_user_edit.TextAlign = 32

$frm_init.Controls.Add($lbl_user_edit)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frm_init.WindowState
#Init the OnLoad event to correct the initial state of the form
$frm_init.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frm_init.ShowDialog()| Out-Null

} #End Function // fertig

# Funktion User editor
function user-editor {
#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$error = "0"
$frm_usr = New-Object System.Windows.Forms.Form
$txb_usr_passwd = New-Object System.Windows.Forms.TextBox
$lbl_usr_pass = New-Object System.Windows.Forms.Label
$btn_usr_create_apply = New-Object System.Windows.Forms.Button
$chbx_disabled = New-Object System.Windows.Forms.CheckBox
$chbx_pw_expires = New-Object System.Windows.Forms.CheckBox
$chbx_cannot_change_pw = New-Object System.Windows.Forms.CheckBox
$chbx_usr_change_pw = New-Object System.Windows.Forms.CheckBox
$lbl_usr_name = New-Object System.Windows.Forms.Label
$txb_usrname = New-Object System.Windows.Forms.TextBox
$txb_last_name = New-Object System.Windows.Forms.TextBox
$lbl_last_name = New-Object System.Windows.Forms.Label
$txb_first_name = New-Object System.Windows.Forms.TextBox
$lbl_first_name = New-Object System.Windows.Forms.Label
$btn_usr_create_cancel = New-Object System.Windows.Forms.Button
$btn_usr_del = New-Object System.Windows.Forms.Button
$lbl_usr = New-Object System.Windows.Forms.Label
$lbl_user_edit = New-Object System.Windows.Forms.Label
$cmb_usr = New-Object System.Windows.Forms.ComboBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.

$btn_usr_create_apply_click= 
{
if($cmb_usr.SelectedIndex -eq "0") { # if "Create New" is selected "index = 0" if index = 0 start Create new User
    #CREATE USER
    if($txb_first_name.text -eq "") { # check if txb is not empty
        $error = "1"
        [System.Windows.Forms.MessageBox]::Show("Bitte Feld Vornamen ausfüllen","error",0)  
    } 
    if($txb_last_name.text -eq "") { # check if txb is not empty
        $error = "1"
        [System.Windows.Forms.MessageBox]::Show("Bitte Feld Nachnamen ausfüllen","error",0)
    } 
    if($txb_usrname.text -eq "") { # check if txb is not empty
        $error = "1"
        [System.Windows.Forms.MessageBox]::Show("Bitte Feld Username ausfüllen","error",0)
    } 
    if($txb_usr_passwd.text -eq "") { # check if txb is not empty
        $error = "1"
        [System.Windows.Forms.MessageBox]::Show("Bitte Feld Passwort ausfüllen","error",0)
    } 
    if($error -eq "0"){ # if no error isset, go ahead
        $testUser = Get-LocalUser | Where-Object {$_.Name -eq $txb_usrname.text}
        if(-not $testUser) { # if User exists, dont go ahead
            $pw = ConvertTo-SecureString $txb_usr_passwd.text -AsPlainText -Force # encrypt Password
            $fullname = $txb_first_name.text,$txb_last_name.text # make first and lastname together
            New-LocalUser $txb_usrname.text -Password $pw -FullName "$fullname" # Create new Localuser
            [System.Windows.Forms.MessageBox]::Show("User erfolgreich erstellt","Success",0) # Display Succes Message
            $txb_usr_passwd.text = "" # Clear txb
            $txb_usrname.text = "" # Clear txb
            $txb_last_name.text = "" # Clear txb
            $txb_first_name.text = "" # Clear txb
        } else {
            [System.Windows.Forms.MessageBox]::Show("User existiert bereits!","error",0) # Display Error Message
        }
    }
    
} else {
    #CHANGE USER
    if($txb_first_name.text -ne "" -and $txb_last_name.text -ne "") { #check if first and lastname isset
        $fullname = $txb_first_name.text, $txb_last_name.text # Create fullname
        $cmb_usr.selectedItem | Set-LocalUser -FullName "$fullname" # set fullname 
        [System.Windows.Forms.MessageBox]::Show("Namen erfolgreich geändert!","Success",0) # Dispaly  Succes message
        $txb_first_name.text = "" # clear txb
        $txb_last_name.text = "" # clear txb
    } elseif($txb_first_name.text -ne "") { # check if first isset
        $cmb_usr.selectedItem | Set-LocalUser -FullName $txb_first_name.text # set fullname
        [System.Windows.Forms.MessageBox]::Show("Namen erfolgreich geändert!","Success",0) # Dispaly  Succes message
        $txb_first_name.text = "" # clear txb
    } elseif($txb_last_name.text -ne "") { # check if lastname isset
        $cmb_usr.selectedItem | Set-LocalUser -FullName $txb_last_name.text # set fullname
        [System.Windows.Forms.MessageBox]::Show("Namen erfolgreich geändert!","Success",0) # Dispaly  Succes message
        $txb_last_name.text = "" # clear txb
    }
    if($txb_usr_passwd.text -ne "") { # check if password isset
        $pw = ConvertTo-SecureString $txb_usr_passwd.text -AsPlainText -Force # encrypt Password
        $cmb_usr.selectedItem | Set-LocalUser -Password $pw
        [System.Windows.Forms.MessageBox]::Show("Passwort erfolgreich geändert!","Success",0) # Dispaly  Succes message 
        $txb_usr_passwd.text = "" # clear txb
    }
    if($txb_usrname.text -ne "") { # check if txb isset
        Rename-LocalUser -Name $cmb_usr.selectedItem -NewName $txb_usrname.text # Remove User
        [System.Windows.Forms.MessageBox]::Show("Username erfolgreich geändert!","Success",0) # Dispaly  Succes message
        $txb_usrname.text = "" # clear txb
    }

} 

}

$btn_usr_create_cancel_click= 
{
    $frm_usr.Close() # close current form

}
 
$btn_usr_del_click= 
{
    if($cmb_usr.SelectedIndex -ne "0") { # if "Create New" is not selected "index = not 0" if index not = 0 start remove User
        Remove-LocalUser -Name $cmb_usr.selectedItem # remove selected user
        [System.Windows.Forms.MessageBox]::Show("User erfolgreich gelöscht!","Success",0) # dispaly Successmessage
    }

}
$handler_frm_usr_Load= 
{
    $useredit_usrname = Get-LocalUser # get localuserdata
    $cmb_usr.Items.add("Create New") # add new "Create User" cmb
    foreach ($name in $useredit_usrname.name) { # get all names
        if($name -eq "Administrator" -or $name -eq "WDAGUtilityAccount" -or $name -eq "Gast" -or $name -eq "DefaultAccount") { # dont display marced users
        } else  {
            $cmb_usr.Items.add($name) # add users to cmb
        }
    }
    $cmb_usr.selectedItem = $cmb_usr.Items[0] # autselect first user with id 0
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$frm_usr.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 401
$System_Drawing_Size.Width = 344
$frm_usr.ClientSize = $System_Drawing_Size
$frm_usr.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_usr.FormBorderStyle = 1
$frm_usr.Name = "frm_usr"
$frm_usr.Text = "User Editor"
$frm_usr.add_Load($handler_frm_usr_Load)

$txb_usr_passwd.DataBindings.DefaultDataSourceUpdateMode = 0
$txb_usr_passwd.PasswordChar = '*'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 148
$System_Drawing_Point.Y = 177
$txb_usr_passwd.Location = $System_Drawing_Point
$txb_usr_passwd.Name = "txb_usr_passwd"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 187
$txb_usr_passwd.Size = $System_Drawing_Size
$txb_usr_passwd.TabIndex = 11

$frm_usr.Controls.Add($txb_usr_passwd)

$lbl_usr_pass.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 177
$lbl_usr_pass.Location = $System_Drawing_Point
$lbl_usr_pass.Name = "lbl_usr_pass"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 129
$lbl_usr_pass.Size = $System_Drawing_Size
$lbl_usr_pass.TabIndex = 10
$lbl_usr_pass.Text = "Password:"
$lbl_usr_pass.TextAlign = 16

$frm_usr.Controls.Add($lbl_usr_pass)


$btn_usr_create_apply.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 371
$btn_usr_create_apply.Location = $System_Drawing_Point
$btn_usr_create_apply.Name = "btn_usr_create_apply"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 160
$btn_usr_create_apply.Size = $System_Drawing_Size
$btn_usr_create_apply.TabIndex = 17
$btn_usr_create_apply.Text = "Apply"
$btn_usr_create_apply.UseVisualStyleBackColor = $True
$btn_usr_create_apply.add_Click($btn_usr_create_apply_click)

$frm_usr.Controls.Add($btn_usr_create_apply)


$chbx_disabled.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 297
$chbx_disabled.Location = $System_Drawing_Point
$chbx_disabled.Name = "chbx_disabled"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 323
$chbx_disabled.Size = $System_Drawing_Size
$chbx_disabled.TabIndex = 15
$chbx_disabled.Text = "Account is disabled"
$chbx_disabled.UseVisualStyleBackColor = $True
$chbx_disabled.add_Click($chbx_disabled_click)
$chbx_disabled.Enabled = $false

$frm_usr.Controls.Add($chbx_disabled)


$chbx_pw_expires.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 269
$chbx_pw_expires.Location = $System_Drawing_Point
$chbx_pw_expires.Name = "chbx_pw_expires"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 323
$chbx_pw_expires.Size = $System_Drawing_Size
$chbx_pw_expires.TabIndex = 14
$chbx_pw_expires.Text = "Password never expires"
$chbx_pw_expires.UseVisualStyleBackColor = $True
$chbx_pw_expires.add_Click($chbx_pw_expires_click)
$chbx_pw_expires.Enabled = $false

$frm_usr.Controls.Add($chbx_pw_expires)


$chbx_cannot_change_pw.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 242
$chbx_cannot_change_pw.Location = $System_Drawing_Point
$chbx_cannot_change_pw.Name = "chbx_cannot_change_pw"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 323
$chbx_cannot_change_pw.Size = $System_Drawing_Size
$chbx_cannot_change_pw.TabIndex = 13
$chbx_cannot_change_pw.Text = "User cannot change password"
$chbx_cannot_change_pw.UseVisualStyleBackColor = $True
$chbx_cannot_change_pw.add_Click($chbx_cannot_change_pw_click)
$chbx_cannot_change_pw.Enabled = $false

$frm_usr.Controls.Add($chbx_cannot_change_pw)


$chbx_usr_change_pw.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 214
$chbx_usr_change_pw.Location = $System_Drawing_Point
$chbx_usr_change_pw.Name = "chbx_usr_change_pw"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 323
$chbx_usr_change_pw.Size = $System_Drawing_Size
$chbx_usr_change_pw.TabIndex = 12
$chbx_usr_change_pw.Text = "User must change password at next logon"
$chbx_usr_change_pw.UseVisualStyleBackColor = $True
$chbx_usr_change_pw.add_Click($chbx_usr_change_pw_click)
$chbx_usr_change_pw.Enabled = $false

$frm_usr.Controls.Add($chbx_usr_change_pw)

$lbl_usr_name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 150
$lbl_usr_name.Location = $System_Drawing_Point
$lbl_usr_name.Name = "lbl_usr_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 129
$lbl_usr_name.Size = $System_Drawing_Size
$lbl_usr_name.TabIndex = 8
$lbl_usr_name.Text = "Username:"
$lbl_usr_name.TextAlign = 16

$frm_usr.Controls.Add($lbl_usr_name)

$txb_usrname.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 148
$System_Drawing_Point.Y = 150
$txb_usrname.Location = $System_Drawing_Point
$txb_usrname.Name = "txb_usrname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 188
$txb_usrname.Size = $System_Drawing_Size
$txb_usrname.TabIndex = 9

$frm_usr.Controls.Add($txb_usrname)

$txb_last_name.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 148
$System_Drawing_Point.Y = 124
$txb_last_name.Location = $System_Drawing_Point
$txb_last_name.Name = "txb_last_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 188
$txb_last_name.Size = $System_Drawing_Size
$txb_last_name.TabIndex = 7

$frm_usr.Controls.Add($txb_last_name)

$lbl_last_name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 124
$lbl_last_name.Location = $System_Drawing_Point
$lbl_last_name.Name = "lbl_last_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 130
$lbl_last_name.Size = $System_Drawing_Size
$lbl_last_name.TabIndex = 6
$lbl_last_name.Text = "Last name:"
$lbl_last_name.TextAlign = 16

$frm_usr.Controls.Add($lbl_last_name)

$txb_first_name.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 148
$System_Drawing_Point.Y = 99
$txb_first_name.Location = $System_Drawing_Point
$txb_first_name.Name = "txb_first_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 189
$txb_first_name.Size = $System_Drawing_Size
$txb_first_name.TabIndex = 5

$frm_usr.Controls.Add($txb_first_name)

$lbl_first_name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 99
$lbl_first_name.Location = $System_Drawing_Point
$lbl_first_name.Name = "lbl_first_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 130
$lbl_first_name.Size = $System_Drawing_Size
$lbl_first_name.TabIndex = 4
$lbl_first_name.Text = "First name:"
$lbl_first_name.TextAlign = 16

$frm_usr.Controls.Add($lbl_first_name)


$btn_usr_create_cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 178
$System_Drawing_Point.Y = 371
$btn_usr_create_cancel.Location = $System_Drawing_Point
$btn_usr_create_cancel.Name = "btn_usr_create_cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 159
$btn_usr_create_cancel.Size = $System_Drawing_Size
$btn_usr_create_cancel.TabIndex = 18
$btn_usr_create_cancel.Text = "Cancel"
$btn_usr_create_cancel.UseVisualStyleBackColor = $True
$btn_usr_create_cancel.add_Click($btn_usr_create_cancel_click)

$frm_usr.Controls.Add($btn_usr_create_cancel)


$btn_usr_del.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 342
$btn_usr_del.Location = $System_Drawing_Point
$btn_usr_del.Name = "btn_usr_del"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_usr_del.Size = $System_Drawing_Size
$btn_usr_del.TabIndex = 16
$btn_usr_del.Text = "Delete user"
$btn_usr_del.UseVisualStyleBackColor = $True
$btn_usr_del.add_Click($btn_usr_del_click)

$frm_usr.Controls.Add($btn_usr_del)

$lbl_usr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 72
$lbl_usr.Location = $System_Drawing_Point
$lbl_usr.Name = "lbl_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 130
$lbl_usr.Size = $System_Drawing_Size
$lbl_usr.TabIndex = 2
$lbl_usr.Text = "Choose user:"
$lbl_usr.TextAlign = 16

$frm_usr.Controls.Add($lbl_usr)

$lbl_user_edit.BorderStyle = 2
$lbl_user_edit.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_user_edit.Font = New-Object System.Drawing.Font("Tahoma",12,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_user_edit.Location = $System_Drawing_Point
$lbl_user_edit.Name = "lbl_user_edit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 325
$lbl_user_edit.Size = $System_Drawing_Size
$lbl_user_edit.TabIndex = 1
$lbl_user_edit.Text = "User Editor"
$lbl_user_edit.TextAlign = 32

$frm_usr.Controls.Add($lbl_user_edit)

$cmb_usr.DataBindings.DefaultDataSourceUpdateMode = 0
$cmb_usr.DropDownStyle = 2
$cmb_usr.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 148
$System_Drawing_Point.Y = 72
$cmb_usr.Location = $System_Drawing_Point
$cmb_usr.Name = "cmb_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 189
$cmb_usr.Size = $System_Drawing_Size
$cmb_usr.TabIndex = 3
$cmb_usr.add_SelectedIndexChanged($cmb_usr_change)

$frm_usr.Controls.Add($cmb_usr)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frm_usr.WindowState
#Init the OnLoad event to correct the initial state of the form
$frm_usr.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frm_usr.ShowDialog()| Out-Null

} #End Function // fertig

# Funktion Group editor
function group-editor {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 03.11.2019 16:59
# Generated By: Aaron
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$frm_grp = New-Object System.Windows.Forms.Form
$btn_add_remove_usr = New-Object System.Windows.Forms.Button
$btn_grp_cancel = New-Object System.Windows.Forms.Button
$btn_grp_add = New-Object System.Windows.Forms.Button
$btn_grp_del = New-Object System.Windows.Forms.Button
$btn_grp_edit = New-Object System.Windows.Forms.Button
$lbl_usr = New-Object System.Windows.Forms.Label
$lbl_user_edit = New-Object System.Windows.Forms.Label
$cmb_grp = New-Object System.Windows.Forms.ComboBox
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$btn_grp_edit_click= 
{
    $selected_grp = $cmb_grp.selectedItem # set selected group
    $frm_grp.Hide() # hide current form
    add-edit-group # open new form
    $frm_grp.Show() # show last form

}

$btn_grp_cancel_click= 
{
    $frm_grp.Close() # Close current form
}

$btn_add_remove_usr_click= 
{
    $selected_grp = $cmb_grp.selectedItem # set selected group
    $frm_grp.Hide() # hide current form
    add-remove-user # open new form
    $frm_grp.Show() # show last form

}

$btn_grp_del_click= 
{
    Remove-LocalGroup -Name $cmb_grp.selectedItem # remove selected localgroup 
    [System.Windows.Forms.MessageBox]::Show("Gruppe erfolgreich gelöscht!","Success",0) #Display success message

}

$btn_grp_add_click=
{
    $frm_grp.Hide() # hide current form
    create_grp # open new form
    $frm_grp.Show() # show last form
}

$handler_frm_grp_Load= 
{
    $grpedit_grps = Get-LocalGroup # set local group in var
    foreach ($name in $grpedit_grps.name) { # get all names
        if($name -eq "Administratoren" -or $name -eq "Zugriffssteuerungs-Unterstützungsoperatoren" -or $name -eq "Distributed COM-Benutzer" -or $name -eq "Ereignisprotokollleser" -or $name -eq "Gerätebesitzer" -or $name -eq "Gäste" -or $name -eq "Hauptbenutzer" -or $name -eq "Hyper-V-Administratoren" -or $name -eq "IIS_IUSRS" -or $name -eq "Kryptografie-Operatoren" -or $name -eq "Leistungsprotokollbenutzer" -or $name -eq "Leistungsüberwachungsbenutzer" -or $name -eq "Netzwerkkonfigurations-Operatoren" -or $name -eq "Remotedesktopbenutzer" -or $name -eq "Remoteverwaltungsbenutzer" -or $name -eq "Replikations-Operator" -or $name -eq "Sicherungs-Operatoren" -or $name -eq "System Managed Accounts Group") { #dont show selected items
        } else  {
            $cmb_grp.Items.add($name) #add names to cmb
        }
    }
    $cmb_grp.selectedItem = $cmb_grp.Items[0] # select first item with id 0

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$frm_grp.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 250
$System_Drawing_Size.Width = 349
$frm_grp.ClientSize = $System_Drawing_Size
$frm_grp.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_grp.FormBorderStyle = 1
$frm_grp.Name = "frm_grp"
$frm_grp.Text = "Group Editor"
$frm_grp.add_Load($handler_frm_grp_Load)


$btn_add_remove_usr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 167
$btn_add_remove_usr.Location = $System_Drawing_Point
$btn_add_remove_usr.Name = "btn_add_remove_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_add_remove_usr.Size = $System_Drawing_Size
$btn_add_remove_usr.TabIndex = 7
$btn_add_remove_usr.Text = "Add or remove user to/from group"
$btn_add_remove_usr.UseVisualStyleBackColor = $True
$btn_add_remove_usr.add_Click($btn_add_remove_usr_click)

$frm_grp.Controls.Add($btn_add_remove_usr)


$btn_grp_cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 220
$btn_grp_cancel.Location = $System_Drawing_Point
$btn_grp_cancel.Name = "btn_grp_cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_grp_cancel.Size = $System_Drawing_Size
$btn_grp_cancel.TabIndex = 5
$btn_grp_cancel.Text = "Cancel"
$btn_grp_cancel.UseVisualStyleBackColor = $True
$btn_grp_cancel.add_Click($btn_grp_cancel_click)

$frm_grp.Controls.Add($btn_grp_cancel)

$btn_grp_add.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 195
$btn_grp_add.Location = $System_Drawing_Point
$btn_grp_add.Name = "btn_grp_add"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_grp_add.Size = $System_Drawing_Size
$btn_grp_add.TabIndex = 6
$btn_grp_add.Text = "Erstellen"
$btn_grp_add.UseVisualStyleBackColor = $True
$btn_grp_add.add_Click($btn_grp_add_click)

$frm_grp.Controls.Add($btn_grp_add)


$btn_grp_del.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 138
$btn_grp_del.Location = $System_Drawing_Point
$btn_grp_del.Name = "btn_grp_del"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_grp_del.Size = $System_Drawing_Size
$btn_grp_del.TabIndex = 4
$btn_grp_del.Text = "Delete"
$btn_grp_del.UseVisualStyleBackColor = $True
$btn_grp_del.add_Click($btn_grp_del_click)

$frm_grp.Controls.Add($btn_grp_del)


$btn_grp_edit.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 109
$btn_grp_edit.Location = $System_Drawing_Point
$btn_grp_edit.Name = "btn_grp_edit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_grp_edit.Size = $System_Drawing_Size
$btn_grp_edit.TabIndex = 3
$btn_grp_edit.Text = "Edit"
$btn_grp_edit.UseVisualStyleBackColor = $True
$btn_grp_edit.add_Click($btn_grp_edit_click)

$frm_grp.Controls.Add($btn_grp_edit)

$lbl_usr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 72
$lbl_usr.Location = $System_Drawing_Point
$lbl_usr.Name = "lbl_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 130
$lbl_usr.Size = $System_Drawing_Size
$lbl_usr.TabIndex = 2
$lbl_usr.Text = "Choose Group"
$lbl_usr.TextAlign = 16

$frm_grp.Controls.Add($lbl_usr)

$lbl_user_edit.BorderStyle = 2
$lbl_user_edit.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_user_edit.Font = New-Object System.Drawing.Font("Tahoma",12,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_user_edit.Location = $System_Drawing_Point
$lbl_user_edit.Name = "lbl_user_edit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 325
$lbl_user_edit.Size = $System_Drawing_Size
$lbl_user_edit.TabIndex = 1
$lbl_user_edit.Text = "Group Editor"
$lbl_user_edit.TextAlign = 32

$frm_grp.Controls.Add($lbl_user_edit)

$cmb_grp.DataBindings.DefaultDataSourceUpdateMode = 0
$cmb_grp.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 148
$System_Drawing_Point.Y = 72
$cmb_grp.Location = $System_Drawing_Point
$cmb_grp.Name = "cmb_grp"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 189
$cmb_grp.Size = $System_Drawing_Size
$cmb_grp.TabIndex = 0

$frm_grp.Controls.Add($cmb_grp)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frm_grp.WindowState
#Init the OnLoad event to correct the initial state of the form
$frm_grp.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frm_grp.ShowDialog()| Out-Null

} #End Function // fertig

# Funktion Add group / Remove Group
function add-remove-user {
#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$frm_add_remove_user = New-Object System.Windows.Forms.Form
$cmb_usrname = New-Object System.Windows.Forms.ComboBox
$btn_add_usr = New-Object System.Windows.Forms.Button
$btn_remove_usr = New-Object System.Windows.Forms.Button
$btn_add_remove_usr_cancel = New-Object System.Windows.Forms.Button
$lbl_usrname = New-Object System.Windows.Forms.Label
$lbl_add_remove_usr = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$btn_add_usr_click= 
{
    $usr_nm = $cmb_usrname.selectedItem # set cmb username in var
    $group = $selected_grp # take selected group in var
    $isInGroup = (Get-LocalGroupMember $group).Name -contains $user # check if user is in group
    if($isInGroup -eq $false) { # if user is in dont group, continue
        Add-LocalGroupMember -Group $selected_grp -Member $usr_nm # add selected user to selected group
        [System.Windows.Forms.MessageBox]::Show("$usr_nm erfolgreich zu $selected_grp hinzugefügt!","Success",0) # Display Successmessage
    } else {
        [System.Windows.Forms.MessageBox]::Show("Fehlgeschlagen, $usr_nm ist bereits in der Gruppe: $selected_grp","Error",0) # Display error message
    }
}

$btn_add_remove_usr_cancel_click= 
{
    $frm_add_remove_user.Close() # close current form

}

$btn_remove_usr_click= 
{
    $usr_nm = $cmb_usrname.selectedItem # set cmb username in var
    $user = "$env:computername\$usr_nm" # get computername
    $group = $selected_grp # take selected group in var
    $isInGroup = (Get-LocalGroupMember $group).Name -contains $user # check if user is in group
    if($isInGroup -eq $true) {  # if user is in group, continue
        Remove-LocalGroupMember -Group $selected_grp -Member $usr_nm # remove localuser
        [System.Windows.Forms.MessageBox]::Show("$usr_nm erfolgreich aus $selected_grp entfernt!","Success",0) # Display Successmessage
    } else {
        [System.Windows.Forms.MessageBox]::Show("Fehlgeschlagen, $usr_nm ist nicht in der Gruppe: $selected_grp","Error",0) # Display Error Message
    }

}

$handler_frm_add_remove_user_Load= 
{
    $useredit_usrname = Get-LocalUser # get username
    foreach ($name in $useredit_usrname.name) { # get all names 
        if($name -eq "Administrator" -or $name -eq "WDAGUtilityAccount" -or $name -eq "Gast" -or $name -eq "DefaultAccount") { #dont display selected items
        } else  {
            $cmb_usrname.Items.add($name) # add selected items
        }
    }
    $cmb_usrname.selectedItem = $cmb_usrname.Items[0] # use first item as display

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$frm_add_remove_user.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 162
$System_Drawing_Size.Width = 349
$frm_add_remove_user.ClientSize = $System_Drawing_Size
$frm_add_remove_user.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_add_remove_user.FormBorderStyle = 1
$frm_add_remove_user.Name = "frm_add_remove_user"
$frm_add_remove_user.Text = "Group Editor"
$frm_add_remove_user.add_Load($handler_frm_add_remove_user_Load)

$cmb_usrname.DataBindings.DefaultDataSourceUpdateMode = 0
$cmb_usrname.FormattingEnabled = $True
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 72
$cmb_usrname.Location = $System_Drawing_Point
$cmb_usrname.Name = "cmb_usrname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 190
$cmb_usrname.Size = $System_Drawing_Size
$cmb_usrname.TabIndex = 3

$frm_add_remove_user.Controls.Add($cmb_usrname)


$btn_add_usr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 14
$System_Drawing_Point.Y = 99
$btn_add_usr.Location = $System_Drawing_Point
$btn_add_usr.Name = "btn_add_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 157
$btn_add_usr.Size = $System_Drawing_Size
$btn_add_usr.TabIndex = 4
$btn_add_usr.Text = "Add user"
$btn_add_usr.UseVisualStyleBackColor = $True
$btn_add_usr.add_Click($btn_add_usr_click)

$frm_add_remove_user.Controls.Add($btn_add_usr)


$btn_remove_usr.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 177
$System_Drawing_Point.Y = 99
$btn_remove_usr.Location = $System_Drawing_Point
$btn_remove_usr.Name = "btn_remove_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 162
$btn_remove_usr.Size = $System_Drawing_Size
$btn_remove_usr.TabIndex = 5
$btn_remove_usr.Text = "Remove user"
$btn_remove_usr.UseVisualStyleBackColor = $True
$btn_remove_usr.add_Click($btn_remove_usr_click)

$frm_add_remove_user.Controls.Add($btn_remove_usr)


$btn_add_remove_usr_cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 14
$System_Drawing_Point.Y = 128
$btn_add_remove_usr_cancel.Location = $System_Drawing_Point
$btn_add_remove_usr_cancel.Name = "btn_add_remove_usr_cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_add_remove_usr_cancel.Size = $System_Drawing_Size
$btn_add_remove_usr_cancel.TabIndex = 6
$btn_add_remove_usr_cancel.Text = "Cancel"
$btn_add_remove_usr_cancel.UseVisualStyleBackColor = $True
$btn_add_remove_usr_cancel.add_Click($btn_add_remove_usr_cancel_click)

$frm_add_remove_user.Controls.Add($btn_add_remove_usr_cancel)

$lbl_usrname.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 72
$lbl_usrname.Location = $System_Drawing_Point
$lbl_usrname.Name = "lbl_usrname"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 130
$lbl_usrname.Size = $System_Drawing_Size
$lbl_usrname.TabIndex = 2
$lbl_usrname.Text = "Username"
$lbl_usrname.TextAlign = 16

$frm_add_remove_user.Controls.Add($lbl_usrname)

$lbl_add_remove_usr.BorderStyle = 2
$lbl_add_remove_usr.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_add_remove_usr.Font = New-Object System.Drawing.Font("Tahoma",12,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_add_remove_usr.Location = $System_Drawing_Point
$lbl_add_remove_usr.Name = "lbl_add_remove_usr"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 325
$lbl_add_remove_usr.Size = $System_Drawing_Size
$lbl_add_remove_usr.TabIndex = 1
$lbl_add_remove_usr.Text = "Add or remove user"
$lbl_add_remove_usr.TextAlign = 32

$frm_add_remove_user.Controls.Add($lbl_add_remove_usr)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frm_add_remove_user.WindowState
#Init the OnLoad event to correct the initial state of the form
$frm_add_remove_user.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frm_add_remove_user.ShowDialog()| Out-Null

} #End Function // fertig

# Funktion Edit / Add Group
function add-edit-group {
#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$frm_grp_add_edit = New-Object System.Windows.Forms.Form
$btn_add_edit_grp_apply = New-Object System.Windows.Forms.Button
$txb_grp_description = New-Object System.Windows.Forms.TextBox
$lbl_grp_description = New-Object System.Windows.Forms.Label
$txb_name_grp = New-Object System.Windows.Forms.TextBox
$btn_add_edit_grp_cancel = New-Object System.Windows.Forms.Button
$lbl_grp_name = New-Object System.Windows.Forms.Label
$lbl_add_edit_grp = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.

$btn_add_edit_grp_cancel_click= 
{
    $frm_grp_add_edit.Close() # Close current form

}

$btn_add_edit_grp_apply_click= 
{
    if($txb_grp_description.text -ne "") { # check if txb is not empty
        Set-LocalGroup -Name $selected_grp -Description $txb_grp_description.text #set description
        [System.Windows.Forms.MessageBox]::Show("Beschreiung der Grupe erfolgreich geändert!","Success",0) # Display success message
    }
    if($txb_name_grp.text -ne "") { # check if txb is not empty
        Rename-LocalGroup -Name $selected_grp -NewName $txb_name_grp.text #set  new namee
        [System.Windows.Forms.MessageBox]::Show("Gruppe erfolgreich umbenannt!","Success",0) # Display success message
    }
    if($txb_name_grp.text -eq "" -and $txb_grp_description.text -eq "") {
        [System.Windows.Forms.MessageBox]::Show("Kein Feld ist ausgefüllt!","Error",0) #Display Error MEssage
    }

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$frm_grp_add_edit.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 188
$System_Drawing_Size.Width = 349
$frm_grp_add_edit.ClientSize = $System_Drawing_Size
$frm_grp_add_edit.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_grp_add_edit.FormBorderStyle = 1
$frm_grp_add_edit.Name = "frm_grp_add_edit"
$frm_grp_add_edit.Text = "Add Group"
$frm_grp_add_edit.add_Load($handler_frm_group_add_edit_Load)


$btn_add_edit_grp_apply.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 14
$System_Drawing_Point.Y = 128
$btn_add_edit_grp_apply.Location = $System_Drawing_Point
$btn_add_edit_grp_apply.Name = "btn_add_edit_grp_apply"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 323
$btn_add_edit_grp_apply.Size = $System_Drawing_Size
$btn_add_edit_grp_apply.TabIndex = 9
$btn_add_edit_grp_apply.Text = "Apply"
$btn_add_edit_grp_apply.UseVisualStyleBackColor = $True
$btn_add_edit_grp_apply.add_Click($btn_add_edit_grp_apply_click)

$frm_grp_add_edit.Controls.Add($btn_add_edit_grp_apply)

$txb_grp_description.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 98
$txb_grp_description.Location = $System_Drawing_Point
$txb_grp_description.Name = "txb_grp_description"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 188
$txb_grp_description.Size = $System_Drawing_Size
$txb_grp_description.TabIndex = 8

$frm_grp_add_edit.Controls.Add($txb_grp_description)

$lbl_grp_description.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 14
$System_Drawing_Point.Y = 93
$lbl_grp_description.Location = $System_Drawing_Point
$lbl_grp_description.Name = "lbl_grp_description"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 129
$lbl_grp_description.Size = $System_Drawing_Size
$lbl_grp_description.TabIndex = 7
$lbl_grp_description.Text = "Description"
$lbl_grp_description.TextAlign = 16

$frm_grp_add_edit.Controls.Add($lbl_grp_description)

$txb_name_grp.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 149
$System_Drawing_Point.Y = 73
$txb_name_grp.Location = $System_Drawing_Point
$txb_name_grp.Name = "txb_name_grp"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 188
$txb_name_grp.Size = $System_Drawing_Size
$txb_name_grp.TabIndex = 6

$frm_grp_add_edit.Controls.Add($txb_name_grp)


$btn_add_edit_grp_cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 157
$btn_add_edit_grp_cancel.Location = $System_Drawing_Point
$btn_add_edit_grp_cancel.Name = "btn_add_edit_grp_cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_add_edit_grp_cancel.Size = $System_Drawing_Size
$btn_add_edit_grp_cancel.TabIndex = 5
$btn_add_edit_grp_cancel.Text = "Cancel"
$btn_add_edit_grp_cancel.UseVisualStyleBackColor = $True
$btn_add_edit_grp_cancel.add_Click($btn_add_edit_grp_cancel_click)

$frm_grp_add_edit.Controls.Add($btn_add_edit_grp_cancel)

$lbl_grp_name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 72
$lbl_grp_name.Location = $System_Drawing_Point
$lbl_grp_name.Name = "lbl_grp_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 130
$lbl_grp_name.Size = $System_Drawing_Size
$lbl_grp_name.TabIndex = 2
$lbl_grp_name.Text = "Name"
$lbl_grp_name.TextAlign = 16

$frm_grp_add_edit.Controls.Add($lbl_grp_name)

$lbl_add_edit_grp.BorderStyle = 2
$lbl_add_edit_grp.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_add_edit_grp.Font = New-Object System.Drawing.Font("Tahoma",12,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_add_edit_grp.Location = $System_Drawing_Point
$lbl_add_edit_grp.Name = "lbl_add_edit_grp"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 325
$lbl_add_edit_grp.Size = $System_Drawing_Size
$lbl_add_edit_grp.TabIndex = 1
$lbl_add_edit_grp.Text = "Add or Edit Group"
$lbl_add_edit_grp.TextAlign = 32

$frm_grp_add_edit.Controls.Add($lbl_add_edit_grp)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frm_grp_add_edit.WindowState
#Init the OnLoad event to correct the initial state of the form
$frm_grp_add_edit.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frm_grp_add_edit.ShowDialog()| Out-Null

} #End Function // fertig

# Funktion Create Group
function create_grp {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 03.11.2019 18:29
# Generated By: Aaron
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
#endregion

#region Generated Form Objects
$frm_c_grp = New-Object System.Windows.Forms.Form
$txb_grp_c_des = New-Object System.Windows.Forms.TextBox
$lbl_grp_c_des = New-Object System.Windows.Forms.Label
$lbl_grp_c_name = New-Object System.Windows.Forms.Label
$txb_grp_c_name = New-Object System.Windows.Forms.TextBox
$btn_grp_create_apply = New-Object System.Windows.Forms.Button
$btn_grp_create_cancel = New-Object System.Windows.Forms.Button
$lbl_user_edit = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$btn_grp_create_cancel_click= 
{
$frm_c_grp.Close() # close curent form

}

$btn_grp_create_create_click= 
{
    $error = "false" # set error false
    if($txb_grp_c_name.text -eq "") { # check if txb is empty
        $error = "true" #set error to true
    }
    if($error -eq "false") { # check if error is false
        New-LocalGroup -Name $txb_grp_c_name.text -Description $txb_grp_c_des.text # create new group
        [System.Windows.Forms.MessageBox]::Show("Gruppe erfolgreich erstellt","Success",0) # Display Successmessage
    } else {
        [System.Windows.Forms.MessageBox]::Show("Nicht alle felder ausgefüllt","Error",0) # Display errormesage
    }

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$frm_c_grp.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 179
$System_Drawing_Size.Width = 349
$frm_c_grp.ClientSize = $System_Drawing_Size
$frm_c_grp.DataBindings.DefaultDataSourceUpdateMode = 0
$frm_c_grp.FormBorderStyle = 1
$frm_c_grp.Name = "frm_c_grp"
$frm_c_grp.Text = "Group Creator"
$frm_c_grp.add_Load($handler_frm_grp_Load)

$txb_grp_c_des.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 85
$System_Drawing_Point.Y = 85
$txb_grp_c_des.Location = $System_Drawing_Point
$txb_grp_c_des.Name = "txb_grp_c_des"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 252
$txb_grp_c_des.Size = $System_Drawing_Size
$txb_grp_c_des.TabIndex = 7

$frm_c_grp.Controls.Add($txb_grp_c_des)

$lbl_grp_c_des.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 85
$lbl_grp_c_des.Location = $System_Drawing_Point
$lbl_grp_c_des.Name = "lbl_grp_c_des"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 60
$lbl_grp_c_des.Size = $System_Drawing_Size
$lbl_grp_c_des.TabIndex = 6
$lbl_grp_c_des.Text = "description"
$lbl_grp_c_des.add_Click($handler_label2_Click)

$frm_c_grp.Controls.Add($lbl_grp_c_des)

$lbl_grp_c_name.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 62
$lbl_grp_c_name.Location = $System_Drawing_Point
$lbl_grp_c_name.Name = "lbl_grp_c_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 42
$lbl_grp_c_name.Size = $System_Drawing_Size
$lbl_grp_c_name.TabIndex = 5
$lbl_grp_c_name.Text = "Name"

$frm_c_grp.Controls.Add($lbl_grp_c_name)

$txb_grp_c_name.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 85
$System_Drawing_Point.Y = 62
$txb_grp_c_name.Location = $System_Drawing_Point
$txb_grp_c_name.Name = "txb_grp_c_name"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 252
$txb_grp_c_name.Size = $System_Drawing_Size
$txb_grp_c_name.TabIndex = 4

$frm_c_grp.Controls.Add($txb_grp_c_name)


$btn_grp_create_apply.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 121
$btn_grp_create_apply.Location = $System_Drawing_Point
$btn_grp_create_apply.Name = "btn_grp_create_apply"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_grp_create_apply.Size = $System_Drawing_Size
$btn_grp_create_apply.TabIndex = 3
$btn_grp_create_apply.Text = "Create"
$btn_grp_create_apply.UseVisualStyleBackColor = $True
$btn_grp_create_apply.add_Click($btn_grp_create_create_click)

$frm_c_grp.Controls.Add($btn_grp_create_apply)


$btn_grp_create_cancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 150
$btn_grp_create_cancel.Location = $System_Drawing_Point
$btn_grp_create_cancel.Name = "btn_grp_create_cancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 325
$btn_grp_create_cancel.Size = $System_Drawing_Size
$btn_grp_create_cancel.TabIndex = 2
$btn_grp_create_cancel.Text = "Cancel"
$btn_grp_create_cancel.UseVisualStyleBackColor = $True
$btn_grp_create_cancel.add_Click($btn_grp_create_cancel_click)

$frm_c_grp.Controls.Add($btn_grp_create_cancel)

$lbl_user_edit.BorderStyle = 2
$lbl_user_edit.DataBindings.DefaultDataSourceUpdateMode = 0
$lbl_user_edit.Font = New-Object System.Drawing.Font("Tahoma",12,0,3,1)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 12
$System_Drawing_Point.Y = 9
$lbl_user_edit.Location = $System_Drawing_Point
$lbl_user_edit.Name = "lbl_user_edit"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 41
$System_Drawing_Size.Width = 325
$lbl_user_edit.Size = $System_Drawing_Size
$lbl_user_edit.TabIndex = 1
$lbl_user_edit.Text = "Group Creator"
$lbl_user_edit.TextAlign = 32
$lbl_user_edit.add_Click($handler_lbl_user_edit_Click)

$frm_c_grp.Controls.Add($lbl_user_edit)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $frm_c_grp.WindowState
#Init the OnLoad event to correct the initial state of the form
$frm_c_grp.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$frm_c_grp.ShowDialog()| Out-Null

} #End Function

main
